### ISSUE TITLE
api.predictthesky.org does not resolve

### ISSUE THREAD

**Issue by JasonLunn** [PredictTheSky/api#1]
```
$ dig api.predictthesky.org

; <<>> DiG 9.8.3-P1 <<>> api.predictthesky.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 5316
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;api.predictthesky.org.     IN  A

;; AUTHORITY SECTION:
predictthesky.org.  1722    IN  SOA a.dns.gandi.net. hostmaster.gandi.net. 1421442737 10800 3600 604800 10800

;; Query time: 31 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Apr  5 15:35:34 2015
;; MSG SIZE  rcvd: 101

```

**Comment by nickcharlton** [comment]
Yeah, indeed.

It's been a bit on hold for the past year or so — the perennial problem of projects started at hack days.
This organisation really represents a bit refactoring of what we'd originally hoped to come out with, and I'm pretty sure the old thrown together one isn't online any more.

That said; I've just merged in a ton of improvements to the library that's planned to back this and so we're on the road to having something working. I'd expect to see a few more things happening here in the next few weeks!

**Comment by JasonLunn** [comment]
Well, at a minimum, can I suggest that you update the page at `http://predictthesky.org/developers.html` to remove references to the non-existant host?
I don't know if you realize this, but Predict The Sky is still listed on `https://data.nasa.gov/developer`, which is how I found it. If the api repository (which is completely empty?) won't be updated for a while in a way that would allow people to host their own endpoint, and the hostname doesn't resolve to a hosted version of the service, consider contacting the appropriate folks at NASA to have them remove the link.

**Comment by nickcharlton** [comment]
Yes, that's a good shout. iirc, it's been listed for a little while (before we'd started looking at rebuilding parts of it) as it'd been originally worked on at the first [Space Apps Challenge](https://spaceappschallenge.org). This weekend has been another one of them and this time interest seems to have picked up quite a bit.

I'll put this issue on hold for now, but I'll get the site updated to make it clear what's going on.
